application: nbacluster
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /assets
  static_dir: assets
- url: /cluster/.*
  script: cluster.app
- url: /games/.*
  script: games.app
- url: /show/.*
  script: show.app
- url: /projections/.*
  script: projections.app
- url: /players/.*
  script: players.app
- url: /teams/.*
  script: teams.app
- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
- name: numpy
  version: latest
- name: matplotlib
  version: latest
- name: jinja2
  version: latest